# Generated by Django 4.1.1 on 2022-10-31 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoboFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RoboChat_Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fuser.friendsuser')),
                ('r_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='robo.robofriend')),
            ],
        ),
        migrations.CreateModel(
            name='RoboChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.TextField()),
                ('chatTime', models.DateTimeField()),
                ('senderId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msgSender', to='robo.robochat_thread')),
                ('threadId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='robo.robochat_thread')),
            ],
        ),
    ]
