# Generated by Django 4.1.1 on 2022-12-12 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robochat',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='robochat',
            name='senderId',
        ),
        migrations.RemoveField(
            model_name='robochat_thread',
            name='r_id',
        ),
        migrations.AddField(
            model_name='robochat',
            name='robo_chat',
            field=models.TextField(default=None, max_length=10000000),
        ),
        migrations.AddField(
            model_name='robochat',
            name='user_chat',
            field=models.TextField(default=None, max_length=10000000),
        ),
        migrations.AlterField(
            model_name='robochat',
            name='chatTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='RoboFriend',
        ),
    ]
