# Generated by Django 4.1.1 on 2022-10-31 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('dOB', models.DateField()),
                ('f_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=50)),
                ('f_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fuser.friendsuser')),
            ],
        ),
        migrations.CreateModel(
            name='FriendsWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person2', to='fuser.profile')),
                ('b_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person1', to='fuser.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FriendsChat_Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fChat', models.TextField()),
                ('fChatTime', models.DateTimeField()),
                ('sender_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fuser.friendswith')),
                ('threadId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Thread', to='fuser.friendswith')),
            ],
        ),
    ]
