# Generated by Django 4.1.1 on 2022-11-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0002_rename_f_name_friendsuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendsuser',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
