# Generated by Django 4.1.1 on 2022-12-09 09:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fuser', '0003_alter_friendsuser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendsuser',
            old_name='birth_date',
            new_name='dOB',
        ),
        migrations.RenameField(
            model_name='friendsuser',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='friendsuser',
            old_name='last_name',
            new_name='l_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='default.png', null=True, upload_to='picture'),
        ),
        migrations.AlterField(
            model_name='friendschat_thread',
            name='fChat',
            field=models.TextField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='friendschat_thread',
            name='fChatTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='friendsuser',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='friendswith',
            name='a_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendswith',
            name='b_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
