# Generated by Django 4.1.1 on 2022-12-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0005_remove_profile_bio_profile_user_alter_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
